### ISSUE TITLE
Support high intensity ANSI colors

### ISSUE THREAD

**Issue by sumdog** [dblock/jenkins-ansicolor-plugin#16]
Does the plugin only support certain ANSI colors? I was looking through the source code and couldn't understand where the actual ANSI parsing/matching with the color map occurred. I only get stripped output. This is the HTML that gets generated:

```
<pre>
[94m[[92m ok [94m][0m Test Search Body Text: "Not Allowed" passed [ ok ]
<span style="display: none;"> Test Search Body Text: "Not Allowed" passed [94m[[92m ok [94m][0m </span>
Sensor DELETE Test
<span style="display: none;"> [95mSensor DELETE Test[0m </span>
Test Status 405 Method Not Allowed passed [ ok ]
<span style="display: none;"> Test Status 405 Method Not Allowed passed [94m[[92m ok [94m][0m </span>
Test Search Body Text: "Not Allowed" passed [ ok ]
<span style="display: none;"> Test Search Body Text: "Not Allowed" passed [94m[[92m ok [94m][0m </span>
Sensor GET without ID Test
<span style="display: none;"> [95mSensor GET without ID Test[0m </span>
Test Status 400 Bad Request passed [ ok ] 
```

http://imgur.com/pdZsT

**Comment by marlene01** [comment]
Hello everyone,

I also need the high intensity colour support, to make the Jenkins console output show the colours of portage.

I got this working locally by doing the following steps:

- The ansicolor plugin has a dependency to jansi-1.9 - in this version the colours form 90 to 97 are not supported. In the latest version of jansi which is the 1.12 - they are supported.
- The ansicolor POM file has to get the latest version of jansi.

```
<dependency>
      <groupId>org.fusesource.jansi</groupId>
      <artifactId>jansi</artifactId>
      <version>1.12</version>
</dependency> 
```
The Class AnsiHtmlOutputStream.java of the ansicolor plugin needs to be extended by a Method that handles the new call from the jansi Class AnsiOutputStream.java, Method processEscapeCommand line 281


AnsiOutputStream.java (from jansi)
`

    @Override
	protected void processSetForegroundColor(int color, boolean bright) throws IOException {
		closeTagOfType(AnsiAttrType.BG); // Strictly not needed, but makes for cleaner HTML.
	    openTag(new AnsiAttributeElement(AnsiAttrType.BG, "span", "style=\"color: " + colorMap.getBright(color) + ";\"")); 	    
	}`

`
...
else if ( 90 <= value && value <= 97 ) { 
     processSetForegroundColor(value-90, true);
...`

AnsiHtmlOutputStream.java (class of anisicolor)


- But this change alone is not working, because jenkins-core also has a dependency to the 1.9 version of jansi.
- The dependency in the POM of jenkins-core also has to be changed to get the latest 1.12 version of jansi. 
- Now build ansicolor, build local jenkins sources and use the local build ansicolor plugin version in /var/lib/jenkins/plugins -> Then the coloured console output is working.

I think this is something which other users also need. Can this be included in the ansicolor plugin and jenkins-core?

**Comment by dblock** [comment]
I cannot comment about jenkins-core, but I would like a pull request for the part here, please. 

I didn't know about the jenkins-core dependency on jansi. I would dig up why it's there at all, seems like this kinds of dependencies can break all kinds of plugins.

**Comment by marlene01** [comment]
I made a branch for my changes, but I can't push it to your git repo:

remote: Permission to dblock/jenkins-ansicolor-plugin.git denied to marlene01.
fatal: unable to access 'https://github.com/dblock/jenkins-ansicolor-plugin.git/': The requested URL returned error: 403

Can you give me the permission? How can I do a pull request?

**Comment by dblock** [comment]
See https://help.github.com/articles/using-pull-requests/. Also https://github.com/dblock/jenkins-ansicolor-plugin/blob/master/CONTRIBUTING.md.

**Comment by marlene01** [comment]
I created a pull request with the information from the 2 tutorials. 
The Number is: #72

**Comment by hashar** [comment]
Thank you @marlene01 and @dblock !

On #16 has been mentioned that Jenkins core has jansi has a dependency already. Looking at core pom it seems to be added as a transitive dependency of Groovy. The last related commit is https://github.com/jenkinsci/jenkins/commit/ae2fe03591c8b44d04edbda14c47def6ab813ee5 which bumps Jansi from 1.9 to 1.11.

That version bump is not included in Jenkins 1.x but is since Jenkins 2.0:
```
$ git tag --contains ae2fe035
jenkins-2.0
...
```
